### ISSUE TITLE
lakefile not found error

### ISSUE THREAD

**Issue by Seasawher** [oliver-butterley/lean-update#11]
in this repository: https://github.com/Seasawher/mathlib4-tactics

I have a following error:

![image](https://github.com/oliver-butterley/lean-update-action/assets/47292598/9fea5a2a-e16b-4894-b2d8-d61c91d41d70)

but obviously `lakefile.lean` exists

**Comment by oliver-butterley** [comment]
Thanks for opening the issue, this is a bug, absolutely not the intended behaviour. I will investigate now.

**Comment by oliver-butterley** [comment]
All fine, wasn't a problem with the action, the workflow that used it needed to add the checkout step prior to using this action. https://github.com/Seasawher/mathlib4-tactics/pull/5
