### ISSUE TITLE
run `lake test`

### ISSUE THREAD

**Issue by Seasawher** [oliver-butterley/lean-update#16]
`lake test` need to be executed.

I think this should be done by https://github.com/leanprover/lean-action.

(There should be a function in lenprover/lean-action to automatically check whether test_runner is registered or not. I created a PR for leanprover/lean-action)

**Comment by Seasawher** [comment]
related: https://github.com/leanprover/lean-action/pull/55

**Comment by oliver-butterley** [comment]
Yes, I absolutely agree, it should use lean-action and also run the test. When I last looked it seemed that the test functionality of lean-action wasn't yet working properly. As soon as it is ready and functioning this should be standard.

**Comment by Seasawher** [comment]
good news!
see: https://github.com/leanprover/lean-action/pull/61

**Comment by oliver-butterley** [comment]
Looks good! As far as I see, it will work fine if we just use lean-action with the auto-config option.
