### ISSUE TITLE
bug: `Get Mathlib Cache` fails

### ISSUE THREAD

**Issue by Seasawher** [oliver-butterley/lean-update#21]
Sometimes workflow fails with error message such that:

```
▼ Run : Get Mathlib Cache
  : Get Mathlib Cache
  echo "::group::Mathlib Cache"
  lake exe cache get
  echo "::endgroup::"
  echo
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
▼ Mathlib Cache
  info: mdgen: updating repository '././.lake/packages/mdgen' to revision '6a6a412465e82572f6e30385592eac52ab055c83'
  info: mathlib: updating repository '././.lake/packages/mathlib' to revision '03092720f68254315c95a5bf2[49](https://github.com/lean-ja/tactic-cheatsheet/actions/runs/9530357340/job/26270125659#step:5:55)c5f2cdef717d6'
  error: external command 'git' exited with code 1
  Error: Process completed with exit code 1.
```

see: https://github.com/leanprover/lean-action/issues/62

**Comment by Seasawher** [comment]
The cause of this is already known: it is due to the use of the github cache in the lean-action.

see: https://github.com/leanprover/lean-action/issues/62#issuecomment-2174583900

**Comment by Seasawher** [comment]
This problem is said to be temporary, but may still persist. I have confirmed that temporarily setting the lean-action's `use-github-cache` option to `false` solves the problem.

@oliver-butterley What shall we do? Setting use-github-cache to false does not cause a serious slowdown, so I prefer to avoid the problem by not using the github cache in the current situation.

**Comment by oliver-butterley** [comment]
Avoiding github cache is fine in my opinion. Just from academic curiosity, I would love to fully understand why this error happens. At the moment it is completely mysterious to me. Is it related to having an action used within another action?

**Comment by Seasawher** [comment]
> Just from academic curiosity, I would love to fully understand why this error happens.

Sorry for my late reply.
I don't understand it either. The only hints I have are the following issue communications.

* https://github.com/leanprover/lean-action/issues/62
* https://github.com/leanprover/lean-action/issues/64
