### ISSUE TITLE
Exception calling ".ctor" with "1" argument(s): "The input string '' was      | not in a correct format."

### ISSUE THREAD

**Issue by pitmonticone** [oliver-butterley/lean-update#39]
It returns this error in all projects I've adopted `lean-update`: https://github.com/ImperialCollegeLondon/FLT/actions/runs/11176285474/job/31069319185#step:3:1.

I'll take a more serious look at it in the next days because I really have no time left.

**Comment by oliver-butterley** [comment]
This appears a duplicate of issue #37

We closed it with the pr earlier today. Can you try running the action again in the problem repos with the new release?

https://github.com/oliver-butterley/lean-update/issues/37

**Comment by pitmonticone** [comment]
Oh sorry. Didn't notice. 

I'll run them and let you know.

**Comment by pitmonticone** [comment]
It works fine now. Thanks a lot!

**Comment by oliver-butterley** [comment]
Thank you for all the testing and feedback
