### ISSUE TITLE
stable Lean (not specified) installed?

### ISSUE THREAD

**Issue by Seasawher** [oliver-butterley/lean-update#6]
Thanks for making nice GitHub Action!

I tested this action for my project https://github.com/Seasawher/SelectionSort.lean, but I got an error in CI.

Action's log is here: https://github.com/Seasawher/SelectionSort.lean/actions/runs/9067085599/job/24911408890

> info: syncing channel updates for 'stable'
info: latest update on stable, lean version v4.7.0
info: downloading component 'lean'
info: installing component 'lean'
info: default toolchain set to 'stable'
>
>  stable installed - Lean (version 4.7.0, x86_64-unknown-linux-gnu, commit 6fce8f7d5cd1, Release)

Lean version in the `lean-toolchain` file is `v4.8.0-rc1`, but installed Lean version is `v4.7.0` as shown above. why different toolchain installed?

**Comment by Seasawher** [comment]
I do not know the cause of why this CI fails. It may not be because of this Action.

**Comment by oliver-butterley** [comment]
:thinking: I'll investigate...

**Comment by oliver-butterley** [comment]
So, there was stupid error introduced by me in some of the shell code. Oops. Updated version [v1-alpha.3](https://github.com/oliver-butterley/lean-update-action/releases/tag/v1-alpha.3) solves this issue and also has some other improvements.

PR to update the use of the action in the repo where the error was discovered: https://github.com/Seasawher/SelectionSort.lean/pull/1
